class JupiterSynastryAspects:
    def __init__(self):
        self.aspects = {
            "Jupiter Conjunction Sun": "You'll find that your confidence and life perspective are greatly expanded by your partner. Together, you energize each other's optimism and wisdom, creating a relationship full of mutual encouragement and growth.",
            "Jupiter Opposition Sun": "You might feel tension between your ego and your partner's philosophies. At times, their optimism could feel overwhelming, while they may see you as self-centered. This dynamic can be challenging but ultimately enlightening.",
            "Jupiter Trine Sun": "Your relationship thrives on harmonious expansion and mutual encouragement. You naturally support each other's growth and success, creating a joyful and supportive bond filled with shared adventures and learning.",
            "Jupiter Sextile Sun": "You offer each other gentle expansion and opportunities for growth. Your partner's wisdom and encouragement help you achieve your goals, while they appreciate your positive outlook, fostering a supportive and optimistic dynamic.",
            "Jupiter Square Sun": "Your partner's excessive optimism may clash with your practical approach, leading to tension. You might find their beliefs conflicting with your focused perspective, creating challenges in how you both view success and growth.",
            "Jupiter Conjunction Moon": "Your emotional world and intuition are expanded by your partner, who in turn is nurtured by your emotional warmth. This creates a generous and emotionally fulfilling relationship with shared spiritual or philosophical interests.",
            "Jupiter Opposition Moon": "You may feel overwhelmed by your partner's expansive emotions or philosophies, while they might find you too emotionally limiting. This dynamic can be challenging but offers potential for emotional growth.",
            "Jupiter Trine Moon": "Your relationship benefits from harmonious emotional expansion and nurturing wisdom. You naturally support each other's emotional growth and intuition, creating a warm, supportive, and spiritually-oriented bond.",
            "Jupiter Sextile Moon": "You help each other grow emotionally and spiritually in a gentle and nurturing way. Your partner expands your emotional horizons, while you add depth to their philosophical nature, fostering a supportive and enriching dynamic.",
            "Jupiter Square Moon": "Your partner's excessive emotional expression may clash with your need for emotional security, creating tension. You both might struggle with emotional boundaries and finding a balance in your expressions of feelings.",
            "Jupiter Conjunction Ascendant": "Your partner has a significant positive influence on your self-expression and life direction. This relationship encourages you to expand your horizons and potential, creating an optimistic and growth-oriented dynamic.",
            "Jupiter Opposition Ascendant": "You may feel tension between your natural expression and your partner's expectations or philosophies. At times, you might feel pressured to be more than you are, while they could see you as too limited.",
            "Jupiter Trine Ascendant": "Your relationship is characterized by harmonious encouragement and natural growth. You support each other's development and self-expression, creating an inspiring and growth-oriented bond.",
            "Jupiter Sextile Ascendant": "You offer each other gentle encouragement and opportunities for growth. Your partner's wisdom and opportunities help your self-development, while you bring fresh energy to their expansive nature, fostering a supportive dynamic.",
            "Jupiter Square Ascendant": "Your partner's excessive optimism may clash with your natural expression, creating pressure and unrealistic expectations. You might feel overwhelmed by their vision of growth and achievement.",
            "Jupiter Conjunction Mercury": "Your thinking and communication are expanded by your partner, who helps you articulate wisdom and ideas clearly. This creates an intellectually stimulating relationship with shared learning and philosophical discussions.",
            "Jupiter Opposition Mercury": "You might feel mental tension and conflicting perspectives with your partner. Their broad concepts could feel overwhelming, while they may see you as too detail-oriented, creating challenging but potentially educational dynamics.",
            "Jupiter Trine Mercury": "Your relationship thrives on harmonious intellectual expansion and clear wisdom. You support each other's learning and communication, creating an educational and mentally stimulating bond.",
            "Jupiter Sextile Mercury": "You help each other grow intellectually in a gentle and supportive way. Your partner expands your thinking and knowledge, while you add practical communication skills to their wisdom, fostering a learning-oriented dynamic.",
            "Jupiter Square Mercury": "Your partner's broad concepts may clash with your need for specific details, creating mental overload. You both might struggle with different approaches to knowledge and communication.",
            "Jupiter Conjunction Venus": "Your capacity for love and beauty is expanded by your partner, who brings grace and charm to your optimism. This creates a generous and loving relationship with shared appreciation for art, culture, and pleasure.",
            "Jupiter Opposition Venus": "You might feel tension between your need for harmony and your partner's excessive optimism. At times, their largesse could feel overwhelming, while they may see you as too superficial or pleasure-seeking.",
            "Jupiter Trine Venus": "Your relationship is characterized by harmonious love and generous affection. You support each other's love nature with wisdom and generosity, creating a joyful, loving, and culturally-rich bond.",
            "Jupiter Sextile Venus": "You help each other grow romantically and culturally in a gentle and enriching way. Your partner expands your appreciation for love and beauty, while you add grace and affection to their optimistic nature, fostering a supportive dynamic.",
            "Jupiter Square Venus": "Your partner's excessive generosity may clash with your need for balance and harmony, creating tension. You both might struggle with different approaches to love and values.",
            "Jupiter Conjunction Mars": "Your ambition and energy are expanded by your partner, who energizes your vision and optimism. This creates a dynamic and adventurous relationship with shared enthusiasm for goals and exploration.",
            "Jupiter Opposition Mars": "You might feel tension between your direct action and your partner's broad vision. At times, their optimism could feel frustrating, while they may see you as too impatient, creating challenging dynamics.",
            "Jupiter Trine Mars": "Your relationship thrives on harmonious expansion and energetic wisdom. You support each other's ambitions with encouragement and broad perspective, creating a dynamic, successful, and adventure-oriented bond.",
            "Jupiter Sextile Mars": "You help each other grow and achieve goals in a gentle and motivated way. Your partner expands your goals and perspective, while you add drive and energy to their optimistic plans, fostering an action-oriented dynamic.",
            "Jupiter Square Mars": "Your partner's excessive optimism may clash with your need for immediate action, creating tension. You both might struggle with different approaches to timing and scope of goals and ambitions.",
            "Jupiter Conjunction Jupiter": "You share optimism and similar approaches to growth and expansion. Your comparable philosophical outlooks create a mutually encouraging and growth-oriented relationship with shared wisdom and optimism.",
            "Jupiter Opposition Jupiter": "You both are optimistic but may disagree on beliefs or methods for growth. This can create tension about different approaches to wisdom and expansion, challenging but potentially enriching.",
            "Jupiter Trine Jupiter": "Your relationship is characterized by harmonious mutual encouragement and shared wisdom. You naturally understand each other's need for growth and expansion, creating a supportive and adventurous bond.",
            "Jupiter Sextile Jupiter": "You appreciate each other's optimism while offering different perspectives on expansion and learning. This creates a supportive and enriching dynamic, complementing each other's approach to growth.",
            "Jupiter Square Jupiter": "You both are optimistic but may disagree on beliefs or approaches to growth, creating tension. This dynamic challenges you to find common ground in your methods of expansion and learning.",
            "Jupiter Conjunction Saturn": "Your partner's expansion is balanced by your practical wisdom, while your discipline is inspired by their optimism. This creates a balanced dynamic between expansion and limitation, fostering steady growth.",
            "Jupiter Opposition Saturn": "You might feel tension between your optimism and your partner's realism. At times, their pessimism could feel restrictive, while they may see you as too unrealistic, creating challenging but potentially balancing dynamics.",
            "Jupiter Trine Saturn": "Your relationship benefits from a harmonious balance between expansion and structure. You provide vision and optimism for your partner's discipline, while they add practical framework to your expansive ideas, creating a wise and balanced bond.",
            "Jupiter Sextile Saturn": "You help each other maintain hope and vision in a gentle and supportive way. Your partner grounds your ideas practically, while you add optimism to their discipline, fostering a balanced dynamic.",
            "Jupiter Square Saturn": "Your partner's expansion may clash with your restrictions, creating tension. You both might struggle with different approaches to timing, scope, and realistic expectations for growth.",
            "Jupiter Conjunction Uranus": "Your partner's expansion combines with your innovation, creating an exciting and progressive relationship. Together, you share an interest in freedom, discovery, and unconventional wisdom, making your bond dynamic and inspiring.",
            "Jupiter Opposition Uranus": "You might feel tension between your traditional wisdom and your partner's revolutionary ideas. At times, their disruptiveness could feel overwhelming, while they may see you as too conventional, creating challenging dynamics.",
            "Jupiter Trine Uranus": "Your relationship thrives on harmonious innovation and progressive wisdom. You support each other's unique ideas with encouragement and broad perspective, creating an inspiring and progressive bond.",
            "Jupiter Sextile Uranus": "You help each other expand unique ideas in a gentle and encouraging way. Your partner adds excitement and innovation to your philosophy, while you provide a broad perspective, fostering a supportive and progressive dynamic.",
            "Jupiter Square Uranus": "Your partner's excessive optimism may clash with your need for independence, creating unpredictable tension. You both might struggle with different approaches to freedom and growth.",
            "Jupiter Conjunction Neptune": "Your partner's wisdom combines with your spirituality, creating an idealistic and spiritually-oriented relationship. Together, you share dreams and a compassionate vision, making your bond deeply meaningful and inspiring.",
            "Jupiter Opposition Neptune": "You might feel tension between your philosophical optimism and your partner's mystical idealism. At times, their vagueness could feel impractical, while they may see you as too materialistic, creating challenging dynamics.",
            "Jupiter Trine Neptune": "Your relationship is characterized by harmonious spiritual expansion and compassionate wisdom. You support each other's spiritual ideals with encouragement and broad perspective, creating an inspiring and spiritually-oriented bond.",
            "Jupiter Sextile Neptune": "You help each other grow spiritually in a gentle and compassionate way. Your partner expands your spiritual vision, while you add sensitivity and intuition to their wisdom, fostering a supportive and enriching dynamic.",
            "Jupiter Square Neptune": "Your partner's philosophical approach may clash with your mystical idealism, creating confusion. You both might struggle with different approaches to what's realistic versus what's possible spiritually.",
            "Jupiter Conjunction Pluto": "Your partner's expansion combines with your transformative power, creating an intense and transformative relationship. Together, you share an interest in deep wisdom and powerful growth, making your bond profoundly impactful.",
            "Jupiter Opposition Pluto": "You might feel tension between your optimistic expansion and your partner's intense transformation. At times, their intensity could feel overwhelming, while they may see you as too superficial, creating challenging dynamics.",
            "Jupiter Trine Pluto": "Your relationship thrives on harmonious transformation and empowering wisdom. You support each other's transformative process with encouragement and broad perspective, creating a powerful and transformative bond.",
            "Jupiter Sextile Pluto": "You help each other grow and transform in a gentle and empowering way. Your partner expands your transformative vision, while you add depth and intensity to their optimism, fostering a supportive and empowering dynamic.",
            "Jupiter Square Pluto": "Your partner's expansive optimism may clash with your intense need for transformation, creating tension. You both might struggle with different approaches to power and growth.",
            "Jupiter Conjunction Medium Coeli": "Your partner's wisdom and optimism align perfectly with your career aspirations and professional growth. They bring opportunities and philosophical insight to your professional endeavors, making your bond instrumental in your professional expansion and recognition.",
            "Jupiter Opposition Medium Coeli": "Your partner's expansive vision may conflict with your practical career limitations. At times, their broad perspective could feel misaligned with your realistic professional constraints, creating tension between visionary thinking and practical achievement.",
            "Jupiter Trine Medium Coeli": "Your partner's wisdom and optimism naturally support your professional goals. They provide excellent guidance and opportunities that enhance your career success, creating a harmonious integration of wisdom and practical achievement.",
            "Jupiter Sextile Medium Coeli": "Your partner has the opportunity to contribute wisdom and expansive perspective to your career development. Their optimism and broad vision can be consciously applied to support your professional growth, offering excellent potential for professional expansion and recognition.",
            "Jupiter Square Medium Coeli": "Your partner's expansive approach may clash with your practical career requirements. At times, their broad vision could feel conflicting with your realistic professional limitations, creating friction between visionary thinking and practical achievement."
        }

    def get_aspect_interpretation(self, aspect_name):
        return self.aspects.get(aspect_name, "Aspect interpretation not found.")

    def add_aspect(self, aspect_name, interpretation):
        self.aspects[aspect_name] = interpretation

    def remove_aspect(self, aspect_name):
        if aspect_name in self.aspects:
            del self.aspects[aspect_name]
