class MediumCoeliSynastryAspects:
    def __init__(self):
        self.aspects = {
            "Medium Coeli Conjunction Sun": "You'll find strong mutual support for each other's ambitions and public image. Your partner naturally enhances your reputation and career prospects, making you feel meant to be seen together publicly. They may become instrumental in your professional success, while you help them achieve recognition.",
            "Medium Coeli Opposition Sun": "You might feel tension between your private identity and public persona. Your authentic self could conflict with your partner's career demands, creating a push-pull dynamic. Balancing success in one area without overshadowing the other requires conscious effort and compromise.",
            "Medium Coeli Trine Sun": "You effortlessly support each other's career goals and public image. There's mutual respect for each other's ambitions, and your individual successes enhance the relationship. Your partner may serve as a valuable advisor in your professional endeavors, reflecting positively on both of you.",
            "Medium Coeli Sextile Sun": "You have opportunities for mutual professional and personal growth through conscious effort. Your partner can provide valuable insights and support for your career development. Collaboration in professional matters and shared involvement in public activities can create productive synergy.",
            "Medium Coeli Square Sun": "You may experience friction between your ego needs and career ambitions. Your identity might feel threatened by your partner's professional goals, or their self-expression could undermine your public image. Addressing power struggles and honoring both individual recognition and shared goals is key.",
            "Medium Coeli Conjunction Moon": "You share deep emotional support for each other's career and public image. Your partner intuitively understands and nurtures your professional ambitions, creating a strong sense of emotional security. They may become the emotional foundation that allows you to pursue your highest achievements.",
            "Medium Coeli Opposition Moon": "You might feel tension between public responsibilities and private emotional needs. Your career demands could conflict with your partner's need for emotional security. Balancing professional commitments with nurturing the relationship requires conscious effort and understanding.",
            "Medium Coeli Trine Moon": "You share a harmonious flow between professional aspirations and emotional fulfillment. Your partner provides intuitive guidance and emotional support that enhances your career success. There's a natural understanding of how to balance public achievements with private emotional needs.",
            "Medium Coeli Sextile Moon": "You have opportunities to blend emotional wisdom with professional goals. Your partner can provide valuable emotional insights that benefit your career development. With conscious effort, your relationship can become a source of both emotional security and professional inspiration.",
            "Medium Coeli Square Moon": "You may experience friction between career demands and emotional needs. Your partner might feel their emotional requirements are incompatible with your professional goals. Honest communication about both professional ambitions and emotional needs is essential for harmony.",
            "Medium Coeli Conjunction Ascendant": "Your career and reputation are intrinsically linked to how your partner presents themselves to the world. They naturally enhance your public image and professional prospects, making you feel meant to be seen together publicly. Your relationship becomes part of your social identity and reputation.",
            "Medium Coeli Opposition Ascendant": "You might feel tension between your public image and your partner's personal presentation. Your professional reputation could feel at odds with their natural way of being. Finding balance between individual authenticity and shared public image is crucial for harmony.",
            "Medium Coeli Trine Ascendant": "You share a harmonious aspect where personal presentation naturally supports professional goals. Your partner's way of being complements and enhances your career aspirations. There's mutual respect for how each of you shows up in the world, benefiting both individual expression and professional achievement.",
            "Medium Coeli Sextile Ascendant": "You have opportunities for mutual enhancement of public image and personal presentation. Your partner can provide valuable insights about self-presentation that benefit your career. With conscious effort, this creates productive synergy between individual authenticity and professional success.",
            "Medium Coeli Square Ascendant": "You may experience friction between how you present yourselves individually and your shared public image. Your partner's natural way of being might seem incompatible with your professional requirements. Compromise and mutual understanding are key to resolving conflicts over image and reputation.",
            "Medium Coeli Conjunction Mercury": "You share excellent communication around career matters and public image. Your partner naturally understands and can articulate your professional goals and aspirations. There's often shared involvement in communication-related careers or public speaking, with your partner serving as a spokesperson or advisor.",
            "Medium Coeli Opposition Mercury": "You might feel tension between communication styles and professional image. Your partner's way of thinking could conflict with your career demands, leading to misunderstandings about professional goals. Aligning communication with career objectives requires conscious effort and understanding.",
            "Medium Coeli Trine Mercury": "You share a harmonious flow between communication and career success. Your partner provides valuable mental support and clear communication that enhances your professional achievements. There's a natural understanding of how to articulate goals and present ideas effectively in professional contexts.",
            "Medium Coeli Sextile Mercury": "You have opportunities for productive communication about career and professional matters. Your partner can provide valuable insights and communication skills that benefit your career development. With conscious effort, this creates excellent collaboration in professional communication.",
            "Medium Coeli Square Mercury": "You may experience friction between communication styles and professional goals. Your partner's way of thinking might seem incompatible with your career requirements, leading to conflicts over how to present ideas publicly. Understanding and compromise are essential for resolving these conflicts.",
            "Medium Coeli Conjunction Venus": "You bring harmony, beauty, and charm to each other's career and public image. Your partner naturally enhances your reputation and social standing, often involving shared interests in arts or relationship-oriented careers. They may become instrumental in your social and professional networking, bringing grace to your public presentation.",
            "Medium Coeli Opposition Venus": "You might feel tension between personal values and professional demands. Your need for harmony could conflict with your partner's career requirements, leading to disagreements over work-life balance. Balancing personal values with career ambitions is crucial for harmony in your relationship.",
            "Medium Coeli Trine Venus": "You share a harmonious aspect where personal values and aesthetic sense naturally support professional goals. Your partner brings charm and social grace that enhances your career success, creating a beautiful integration between love, beauty, and professional achievement.",
            "Medium Coeli Sextile Venus": "You have opportunities to blend personal values and aesthetic sense with professional goals. Your partner can provide valuable insights about presentation and social dynamics that benefit your career. With conscious effort, this creates beautiful harmony between personal fulfillment and professional success.",
            "Medium Coeli Square Venus": "You may experience friction between personal values and professional demands. Your aesthetic or relationship needs might seem incompatible with your partner's career goals, leading to conflicts over work-life balance. Understanding and compromise are essential for resolving these conflicts.",
            "Medium Coeli Conjunction Mars": "You bring dynamic energy and drive to each other's career and public image. Your partner provides powerful motivation and action-oriented support for your professional goals, often involving shared interests in competitive or leadership-oriented careers. They may become the driving force behind your professional achievements.",
            "Medium Coeli Opposition Mars": "You might feel tension between aggressive drive and professional reputation. Your partner's direct energy could conflict with your career demands, leading to disagreements about professional strategies. Channeling this energy constructively is crucial for harmony in your relationship.",
            "Medium Coeli Trine Mars": "You share a harmonious aspect where personal drive and ambition naturally support professional goals. Your partner provides excellent motivation and practical action that enhances your career success, creating a natural understanding of how to achieve goals effectively.",
            "Medium Coeli Sextile Mars": "You have opportunities for productive action toward career goals. Your partner can provide valuable energy and motivation that benefit your professional development. With conscious effort, this creates excellent drive and determination in your professional pursuits.",
            "Medium Coeli Square Mars": "You may experience friction between aggressive drive and professional image. Your partner's approach to action might seem incompatible with your career requirements, leading to conflicts over professional strategies. Understanding and compromise are essential for resolving these conflicts.",
            "Medium Coeli Conjunction Jupiter": "You bring expansion, optimism, and growth to each other's career and public image. Your partner naturally enhances your reputation and opens doors for professional advancement, often involving shared interests in education or international affairs. They may become instrumental in your professional expansion and recognition.",
            "Medium Coeli Opposition Jupiter": "You might feel tension between expansion desires and practical career limitations. Your partner's optimistic vision could conflict with your realistic professional constraints, leading to disagreements about career directions. Balancing vision with practical achievement is crucial for harmony in your relationship.",
            "Medium Coeli Trine Jupiter": "You share a harmonious aspect where wisdom and expansion naturally support professional goals. Your partner provides excellent guidance and opportunities that enhance your career success, creating a natural understanding of how to grow professionally while maintaining ethical standards.",
            "Medium Coeli Sextile Jupiter": "You have opportunities for professional growth and expansion. Your partner can provide valuable wisdom and opportunities that benefit your career development. With conscious effort, this creates excellent potential for professional advancement and recognition.",
            "Medium Coeli Square Jupiter": "You may experience friction between expansion desires and professional realities. Your partner's vision might seem incompatible with your career constraints, leading to conflicts over realistic versus idealistic career goals. Understanding and compromise are essential for resolving these conflicts.",
            "Medium Coeli Conjunction Saturn": "You bring structure, discipline, and long-term planning to each other's career and public image. Your partner provides practical wisdom and strategic thinking that supports your professional development, creating lasting professional achievement and a solid reputation.",
            "Medium Coeli Opposition Saturn": "You might feel tension between structural limitations and professional ambitions. Your partner's practical concerns could conflict with your career aspirations, leading to disagreements about career strategies. Patience and realistic planning are crucial for achieving lasting professional success.",
            "Medium Coeli Trine Saturn": "You share a harmonious aspect where discipline and structure naturally support professional goals. Your partner provides excellent practical guidance and long-term planning that enhances your career success, creating a natural understanding of how to build lasting professional achievement.",
            "Medium Coeli Sextile Saturn": "You have opportunities for structured professional development. Your partner can provide valuable discipline and practical wisdom that benefit your career growth. With conscious effort, this creates an excellent foundation for lasting professional achievement.",
            "Medium Coeli Square Saturn": "You may experience friction between structural limitations and professional ambitions. Your partner's restrictions might seem incompatible with your career goals, leading to conflicts over professional timing or realistic career expectations. Understanding and compromise are essential for resolving these conflicts.",
            "Medium Coeli Conjunction Uranus": "You bring innovation, originality, and sudden changes to each other's career and public image. Your partner encourages you to break free from conventional career paths and embrace unique professional expression, often involving shared interests in technology or humanitarian causes.",
            "Medium Coeli Opposition Uranus": "You might feel tension between innovation and professional stability. Your partner's need for freedom could conflict with your career security needs, leading to disagreements about professional stability versus innovation. Balancing revolutionary impulses with practical career considerations is crucial for harmony.",
            "Medium Coeli Trine Uranus": "You share a harmonious aspect where innovation and originality naturally support professional goals. Your partner provides excellent insights and unique perspectives that enhance your career success, creating a natural understanding of how to innovate professionally while maintaining effectiveness.",
            "Medium Coeli Sextile Uranus": "You have opportunities for innovative professional development. Your partner can provide valuable originality and fresh perspectives that benefit your career advancement. With conscious effort, this creates excellent potential for unique professional breakthroughs.",
            "Medium Coeli Square Uranus": "You may experience friction between innovation and professional stability. Your partner's revolutionary approach might seem incompatible with your career requirements, leading to conflicts over professional security versus freedom and originality. Understanding and compromise are essential for resolving these conflicts.",
            "Medium Coeli Conjunction Neptune": "You bring inspiration, creativity, and spiritual dimension to each other's career and public image. Your partner encourages you to pursue careers that serve higher purposes or involve creativity and compassion, often involving shared interests in arts or spiritual fields.",
            "Medium Coeli Opposition Neptune": "You might feel tension between idealistic vision and practical career reality. Your partner's spiritual vision could conflict with your practical career needs, leading to confusion about professional direction. Grounding inspiration in practical achievement is crucial for harmony in your relationship.",
            "Medium Coeli Trine Neptune": "You share a harmonious aspect where inspiration and creativity naturally support professional goals. Your partner provides excellent artistic vision and spiritual insight that enhances your career success, creating a natural understanding of how to integrate higher purpose with professional achievement.",
            "Medium Coeli Sextile Neptune": "You have opportunities for inspired professional development. Your partner can provide valuable creativity and spiritual perspective that benefit your career growth. With conscious effort, this creates excellent potential for meaningful professional expression.",
            "Medium Coeli Square Neptune": "You may experience friction between idealistic vision and professional reality. Your partner's spiritual approach might seem incompatible with your career requirements, leading to conflicts between practical needs and higher calling. Understanding and compromise are essential for resolving these conflicts.",
            "Medium Coeli Conjunction Pluto": "You bring transformation, power, and intensity to each other's career and public image. Your partner catalyzes profound changes in your professional life and public reputation, often involving shared interests in psychology or transformative fields.",
            "Medium Coeli Opposition Pluto": "You might feel intense tension between transformation and professional stability. Your partner's transformative energy could conflict with your career security needs, leading to power struggles over professional direction. Conscious handling of power dynamics is crucial for harmony in your relationship.",
            "Medium Coeli Trine Pluto": "You share a harmonious aspect where transformation and power naturally support professional goals. Your partner provides excellent depth and transformative insight that enhances your career success, creating a natural understanding of how to use power responsibly and transform professionally.",
            "Medium Coeli Sextile Pluto": "You have opportunities for transformative professional development. Your partner can provide valuable depth and transformative perspective that benefit your career advancement. With conscious effort, this creates excellent potential for profound professional transformation.",
            "Medium Coeli Square Pluto": "You may experience friction between transformation and professional stability. Your partner's intense approach might seem incompatible with your career requirements, leading to power struggles over professional control. Understanding and compromise are essential for resolving these conflicts.",
            "Medium Coeli Conjunction Medium Coeli": "You share career goals and similar professional aspirations, understanding each other's ambitions and working together effectively toward mutual success. There's natural compatibility in life direction and public image, often appearing in business partnerships or supportive relationships.",
            "Medium Coeli Opposition Medium Coeli": "You have complementary but potentially conflicting career paths, with different approaches to professional success or competing ambitions. While this can create tension, respecting each other's different career styles and goals can provide balance and mutual growth.",
            "Medium Coeli Trine Medium Coeli": "You share a harmonious aspect where career goals and professional approaches naturally complement each other. Both of you support each other's professional development and share similar values about success, creating excellent potential for mutual growth and shared achievements.",
            "Medium Coeli Sextile Medium Coeli": "You have opportunities for collaborative professional development, benefiting from each other's career insights and approaches. With conscious effort, this creates productive synergy in professional matters and mutual career advancement.",
            "Medium Coeli Square Medium Coeli": "You may experience friction between different career approaches and professional goals, with conflicting ambitions or ideas about success. Working through this requires compromise and mutual respect for different career paths, fostering understanding and collaboration."
        }

    def get_aspect_interpretation(self, aspect_name):
        return self.aspects.get(aspect_name, "Aspect interpretation not found.")

    def add_aspect(self, aspect_name, interpretation):
        self.aspects[aspect_name] = interpretation

    def remove_aspect(self, aspect_name):
        if aspect_name in self.aspects:
            del self.aspects[aspect_name]
