class MercurySynastryAspects:
    def __init__(self):
        self.aspects = {
            "Mercury Conjunction Sun": "You feel mentally stimulated and inspired by your partner's identity. You can easily understand and articulate their ideas and essence, creating a natural intellectual rapport. You often serve as a communicator or interpreter for their vision.",
            "Mercury Opposition Sun": "You may intellectually challenge or debate your partner's ideas and identity. While this can create stimulating mental exchanges, you might also feel overshadowed by their ego, or vice versa, leading to a dynamic of both tension and growth.",
            "Mercury Trine Sun": "You feel naturally supported and understood by your partner. They appreciate and validate your thoughts and communication style, creating harmonious mental flow and mutual intellectual respect that enhances your confidence.",
            "Mercury Sextile Sun": "You feel gently encouraged and supported by your partner. There's mutual intellectual support, helping each other express ideas more effectively and fostering a cooperative and understanding dynamic.",
            "Mercury Square Sun": "You may feel criticized or misunderstood by your partner's ego. Their identity might clash with your way of thinking, creating intellectual friction or communication breakdowns that require patience and understanding to overcome.",
            "Mercury Conjunction Moon": "You feel emotionally understood and can easily communicate with your partner's feelings. You naturally know how to speak to their emotional needs, while they provide emotional depth to your thoughts, creating a nurturing and intuitive connection.",
            "Mercury Opposition Moon": "You may intellectualize or rationalize your partner's emotions. While this can provide helpful perspective, it might also create tension if you dismiss or analyze away their feelings, requiring sensitivity and balance.",
            "Mercury Trine Moon": "You feel naturally attuned to your partner's emotional communication. There's harmonious flow between thought and feeling, allowing you to understand and express their emotional needs effectively, fostering a deep and supportive bond.",
            "Mercury Sextile Moon": "You feel gently supported by your partner's emotional wisdom. There's mutual understanding, helping each other communicate feelings and thoughts more effectively and creating a caring and empathetic dynamic.",
            "Mercury Square Moon": "You may inadvertently hurt or frustrate your partner through insensitive communication. Their emotional reactions might confuse or overwhelm your logical approach, requiring patience and emotional awareness to navigate.",
            "Mercury Conjunction Ascendant": "You feel immediately understood and can easily communicate with your partner. Their natural way of being resonates with your communication style, creating instant mental rapport and a sense of being on the same wavelength.",
            "Mercury Opposition Ascendant": "You may represent intellectual ideals for your partner, but feel you need to communicate differently or more carefully with them. This dynamic can challenge both of you to grow and adapt in your communication styles.",
            "Mercury Trine Ascendant": "You feel naturally supported and understood by your partner. They enhance your communication confidence and ability to express yourself clearly, fostering an encouraging and harmonious connection.",
            "Mercury Sextile Ascendant": "You feel gently encouraged by your partner. There's mutual support for clear communication and intellectual expression, creating a cooperative and stimulating dynamic that benefits both of you.",
            "Mercury Square Ascendant": "You may feel misunderstood or challenged by your partner's presentation. Their way of being might clash with how you want to communicate, requiring effort and compromise to find common ground.",
            "Mercury Conjunction Venus": "You feel appreciated and loved for your thoughts and communication style. Your partner finds your way of expressing yourself charming and attractive, creating natural harmony between mind and heart with beautiful, loving communication.",
            "Mercury Opposition Venus": "You may feel tension between intellectual expression and romantic values. Your partner might find you too analytical, while you feel they focus too much on harmony over truth, creating a dynamic that requires balance and understanding.",
            "Mercury Trine Venus": "You feel naturally supported and appreciated by your partner. They enhance your communication with warmth and charm, creating harmonious and beautiful expression of thoughts and ideas that deepen your connection.",
            "Mercury Sextile Venus": "You feel gently appreciated and supported by your partner. There's mutual support for beautiful communication, helping each other express thoughts with charm and grace, fostering a pleasant and affectionate dynamic.",
            "Mercury Square Venus": "You may feel your communication style conflicts with your partner's need for harmony. They might find you too critical, while you feel restricted in honest expression, requiring understanding and compromise to resolve.",
            "Mercury Conjunction Mars": "You feel energized and motivated by your partner's passionate energy. They stimulate your thinking and communication, but this can also create heated debates if not channeled constructively, fostering a dynamic and engaging connection.",
            "Mercury Opposition Mars": "You may feel challenged or attacked by your partner's assertive communication style. They might find you too intellectual, while you feel overwhelmed by their directness, requiring patience and mutual respect to navigate.",
            "Mercury Trine Mars": "You feel naturally energized and supported by your partner's passionate energy. They help you express your thoughts with more confidence and conviction, creating dynamic but harmonious communication that strengthens your bond.",
            "Mercury Sextile Mars": "You feel gently encouraged and motivated by your partner. There's mutual support for assertive communication, helping each other express thoughts and ideas with more confidence, fostering a cooperative and empowering dynamic.",
            "Mercury Square Mars": "You may feel attacked or criticized by your partner's aggressive communication style. They might find you too analytical, creating tension and potential for arguments that require understanding and compromise to overcome.",
            "Mercury Conjunction Jupiter": "You feel expanded and inspired by your partner's wisdom and broad perspective. They encourage you to think bigger and communicate with more confidence and optimism, fostering a connection full of growth and possibility.",
            "Mercury Opposition Jupiter": "You may feel overshadowed or judged by your partner's grand ideas. They might find you too focused on details, while you feel overwhelmed by their expansive approach, requiring balance and mutual respect to navigate.",
            "Mercury Trine Jupiter": "You feel naturally supported and inspired by your partner's wisdom and optimism. They enhance your communication with broader perspective, creating harmonious intellectual growth and a sense of shared vision.",
            "Mercury Sextile Jupiter": "You feel gently encouraged and supported by your partner's wisdom. There's mutual support for learning and growth, with them helping you expand your thinking, fostering a dynamic of shared exploration and understanding.",
            "Mercury Square Jupiter": "You may feel judged or criticized by your partner's moral standards. They might find you too narrow-minded, while you feel overwhelmed by their expectations, requiring understanding and compromise to resolve.",
            "Mercury Conjunction Saturn": "You feel both supported and restricted by your partner's structured approach. They provide discipline to your thinking but may also feel critical of your communication style, fostering a dynamic of growth through challenge.",
            "Mercury Opposition Saturn": "You may feel judged or restricted by your partner's critical approach. They might find you too scattered, while you feel controlled, requiring patience and mutual respect to find balance in your communication.",
            "Mercury Trine Saturn": "You feel naturally supported and stabilized by your partner's practical wisdom. They help you organize your thoughts and communicate more effectively, creating a grounded and productive connection.",
            "Mercury Sextile Saturn": "You feel gently supported and encouraged by your partner's stability. There's mutual support for responsible communication and practical thinking, fostering a reliable and cooperative dynamic.",
            "Mercury Square Saturn": "You may feel criticized or blocked by your partner's restrictive approach. They might find you too frivolous, creating tension around communication that requires understanding and compromise to overcome.",
            "Mercury Conjunction Uranus": "You feel excited and liberated by your partner's innovative thinking. They stimulate your mind with original ideas, but this can also create mental instability, fostering a dynamic of creativity and unpredictability.",
            "Mercury Opposition Uranus": "You may feel challenged or disrupted by your partner's unpredictable communication. They might find you too conventional, while you feel overwhelmed by their erratic energy, requiring adaptability and open-mindedness to navigate.",
            "Mercury Trine Uranus": "You feel naturally inspired and liberated by your partner's innovative thinking. They enhance your communication with originality, creating harmonious mental stimulation and a sense of shared excitement for new ideas.",
            "Mercury Sextile Uranus": "You feel gently encouraged and inspired by your partner's original thinking. There's mutual support for innovative communication, fostering a dynamic of creativity and intellectual exploration.",
            "Mercury Square Uranus": "You may feel disrupted or confused by your partner's erratic communication. They might find you too rigid, while you feel scattered, requiring patience and flexibility to find common ground.",
            "Mercury Conjunction Neptune": "You feel inspired and spiritually elevated by your partner's intuitive communication. They enhance your imagination, but this can also create confusion, fostering a dynamic of creativity and spiritual connection that requires clarity and understanding.",
            "Mercury Opposition Neptune": "You may feel confused or deceived by your partner's elusive communication. They might find you too logical, while you feel your clarity is clouded, requiring sensitivity and open dialogue to navigate.",
            "Mercury Trine Neptune": "You feel naturally inspired and spiritually supported by your partner's intuitive wisdom. They enhance your communication with creativity, creating harmonious psychic connection and a deep sense of understanding.",
            "Mercury Sextile Neptune": "You feel gently inspired and supported by your partner's intuitive communication. There's mutual support for creative expression, fostering a dynamic of empathy and spiritual growth.",
            "Mercury Square Neptune": "You may feel confused or misled by your partner's unclear communication. They might find you too analytical, while you feel undermined, requiring patience and clarity to resolve misunderstandings.",
            "Mercury Conjunction Pluto": "You feel powerfully transformed by your partner's deep communication. They stimulate your thinking with profound insights, but this can also feel overwhelming, fostering a dynamic of intensity and psychological depth that requires trust and understanding.",
            "Mercury Opposition Pluto": "You may feel mentally challenged or manipulated by your partner's intense communication. They might find you too superficial, while you feel controlled, requiring mutual respect and open dialogue to navigate.",
            "Mercury Trine Pluto": "You feel naturally empowered by your partner's profound insights. They enhance your communication with depth, creating harmonious mental transformation and a sense of shared understanding that strengthens your bond.",
            "Mercury Sextile Pluto": "You feel gently empowered and supported by your partner's deep insights. There's mutual support for psychological understanding, fostering a dynamic of growth and transformative communication.",
            "Mercury Square Pluto": "You may feel mentally controlled by your partner's intense communication. They might find you too superficial, while you feel invaded, requiring trust and mutual respect to overcome challenges.",
            "Mercury Conjunction Medium Coeli": "Your communication style aligns perfectly with your partner's career needs. You can effectively articulate their professional goals and may become their spokesperson, fostering a dynamic of collaboration and shared intellectual approach to career development.",
            "Mercury Opposition Medium Coeli": "Your communication style may conflict with your partner's professional requirements. You might feel your natural expression doesn't align with their career image, creating tension that requires adaptability and mutual understanding to navigate.",
            "Mercury Trine Medium Coeli": "Your communication abilities naturally support your partner's professional goals. You provide valuable insights and effective communication strategies, creating harmonious intellectual collaboration and a sense of shared purpose in their career success.",
            "Mercury Sextile Medium Coeli": "You have the opportunity to contribute valuable communication skills to your partner's career development. Your ability to think clearly can be consciously applied to support their professional advancement, fostering a dynamic of cooperation and mutual growth.",
            "Mercury Square Medium Coeli": "Your communication style may clash with your partner's professional requirements. You might feel your natural expression undermines their career goals, creating friction that requires understanding and compromise to resolve.",
            "Mercury Conjunction Mercury": "You share strong mental rapport and effortless communication, thinking and expressing yourselves in similar ways. This creates an ideal connection for intellectual and emotional bonding, though it can sometimes lack perspective if both of you think too similarly.",
            "Mercury Opposition Mercury": "You bring intellectual stimulation through contrast, each having different ways of thinking. This can lead to engaging debates or misunderstandings, but with curiosity and patience, it fosters growth by encouraging alternative viewpoints.",
            "Mercury Square Mercury": "You experience a clash in communication styles, leading to frequent misunderstandings. Conversations may feel frustrating unless both of you work on clear, respectful dialogue and stay open to how the other processes information.",
            "Mercury Trine Mercury": "You share easy communication and a natural intellectual connection. Your minds operate in sync, fostering mutual understanding and cooperation, especially in problem-solving or planning, making your relationship feel mentally aligned and fluid.",
            "Mercury Sextile Mercury": "You promote constructive dialogue and intellectual compatibility. There's mutual respect for each other's thoughts, making it easier to collaborate and encourage each other's mental growth with just enough diversity to keep things interesting."
        }

    def get_aspect_interpretation(self, aspect_name):
        return self.aspects.get(aspect_name, "Aspect interpretation not found.")

    def add_aspect(self, aspect_name, interpretation):
        self.aspects[aspect_name] = interpretation

    def remove_aspect(self, aspect_name):
        if aspect_name in self.aspects:
            del self.aspects[aspect_name]
