class MoonSynastryAspects:
    def __init__(self):
        self.aspects = {
            "Moon Conjunction Sun": "You feel emotionally fulfilled and nurtured by your partner's presence. Your instincts and emotional needs align naturally with how they express themselves, creating deep emotional bonding and mutual understanding. You feel secure, and they feel emotionally supported.",
            "Moon Opposition Sun": "Your emotional nature balances your partner's conscious expression, but you might feel emotionally neglected if they focus too much on themselves. You may need to express your emotions more directly, while they learn to be more emotionally sensitive.",
            "Moon Trine Sun": "You feel emotionally supported and understood by your partner. There's a harmonious flow where your emotional needs are naturally met by their way of being, creating easy emotional communication and mutual nurturing.",
            "Moon Sextile Sun": "You can express your emotions comfortably with your partner, and they learn emotional wisdom from you. There's gentle, supportive energy for emotional expression and mutual understanding.",
            "Moon Square Sun": "You may feel emotionally frustrated or unsupported by your partner's self-expression. Your emotional needs might conflict with their ego, requiring conscious effort to balance emotional sensitivity with personal identity.",
            "Moon Conjunction Moon": "You share deep emotional understanding and similar instinctual responses. There's natural empathy and the ability to comfort each other intuitively, though this can sometimes lack emotional growth if both of you reinforce each other's patterns without challenge.",
            "Moon Opposition Moon": "You have complementary emotional approaches, which can create attraction but also require effort to understand each other's emotional needs. One of you may be more nurturing while the other is more independent, creating a dynamic of growth through difference.",
            "Moon Trine Moon": "You share excellent emotional harmony and mutual support. Your emotional needs flow together naturally, creating a sense of emotional security and understanding. There's easy empathy and the ability to provide comfort and nurturing to each other, promoting emotional stability.",
            "Moon Sextile Moon": "You share a gentle, supportive emotional connection. Both of you can understand and support each other's emotional needs without overwhelming intensity, fostering mutual emotional encouragement and care.",
            "Moon Square Moon": "You may experience tension between different emotional needs and expressions. One person's way of expressing emotions might trigger insecurity in the other, but this can also promote emotional growth if you learn to appreciate different emotional styles.",
            "Moon Conjunction Ascendant": "You feel an immediate emotional connection and comfort with your partner. They naturally express qualities that make you feel emotionally safe and understood, creating instant rapport and the feeling of being 'emotionally seen.'",
            "Moon Opposition Ascendant": "You provide deep, nurturing connection to your partner, representing home and emotional security to them. There's potential for you to offer emotional foundation and comfort, but also for your deepest emotional needs to be triggered.",
            "Moon Trine Ascendant": "You feel harmonious emotional expression and acceptance with your partner. They naturally make you feel emotionally comfortable and accepted, enhancing their personality with your emotional nature and fostering easy emotional communication.",
            "Moon Sextile Ascendant": "You feel gently supported by your partner in expressing your emotions. They help you communicate your feelings more confidently, while you provide emotional insight and sensitivity to them, creating mutual emotional encouragement.",
            "Moon Square Ascendant": "You may experience tension between your emotional needs and your partner's outward presentation. Their natural way of being might trigger your emotional insecurities, requiring effort to balance emotional authenticity with social presentation.",
            "Moon Conjunction Mercury": "You share natural emotional communication and mental-emotional harmony with your partner. They can easily understand and articulate your feelings, while you feel heard and emotionally understood, creating intuitive communication and deep emotional intimacy.",
            "Moon Opposition Mercury": "You may feel tension between emotion and logic with your partner. They might rationalize your feelings, while you feel they are too analytical. However, this can create balance if you both appreciate different processing styles, fostering growth through understanding.",
            "Moon Trine Mercury": "You share excellent emotional communication and understanding with your partner. They know how to communicate with your emotional nature, while you provide emotional depth to their thoughts, creating easy sharing of feelings and mutual support.",
            "Moon Sextile Mercury": "You feel supported in emotional expression and communication with your partner. They help you articulate your feelings more clearly, while you provide emotional insight to their thinking, fostering gentle and encouraging communication.",
            "Moon Square Mercury": "You may experience friction between your emotional needs and your partner's communication style. They might hurt your feelings through insensitive communication, while your emotional reactions frustrate their logical approach, requiring balance and understanding.",
            "Moon Conjunction Venus": "You share deep emotional and romantic harmony with your partner. They naturally love and appreciate your emotional nature, while you feel emotionally fulfilled by their affection, creating natural tenderness, caring, and romantic feeling.",
            "Moon Opposition Venus": "You may have complementary energy in emotional and romantic expression with your partner. They might express love differently than you need emotionally, requiring effort to understand each other's love languages but creating growth through learning.",
            "Moon Trine Venus": "You share harmonious emotional and romantic compatibility with your partner. They know how to make you feel loved and emotionally secure, while you provide emotional depth and nurturing to them, creating easy affection and mutual emotional satisfaction.",
            "Moon Sextile Venus": "You feel gentle, supportive energy for love and emotional connection with your partner. They help you feel more beautiful and valued, while you provide emotional warmth and caring to them, fostering mutual affection and harmony.",
            "Moon Square Venus": "You may experience tension between your emotional needs and your partner's expressions of love. Their way of showing affection might not match your emotional needs, requiring effort to understand and appreciate different ways of expressing and receiving love.",
            "Moon Conjunction Mars": "You share intense emotional and physical chemistry with your partner. They are sexually attracted to your emotional nature, while you feel energized and passionate with them, creating strong physical attraction but potential for emotional reactivity.",
            "Moon Opposition Mars": "You may feel dynamic tension between emotion and action with your partner. They might trigger your emotional insecurities, while your emotional needs frustrate their desire for action, creating passionate attraction if balanced properly.",
            "Moon Trine Mars": "You share harmonious emotional and sexual energy with your partner. They support and energize your emotional expression, while you provide emotional depth to their passionate nature, creating comfortable physical chemistry and mutual satisfaction.",
            "Moon Sextile Mars": "You feel gentle, supportive energy for emotional and physical connection with your partner. They help you feel more confident and assertive, while you provide emotional insight to them, fostering mutual encouragement and comfortable attraction.",
            "Moon Square Mars": "You may experience friction between your emotional needs and your partner's assertive energy. They might be too aggressive for your emotional comfort, while your reactions frustrate their direct approach, creating potential for arguments but also passionate intensity.",
            "Moon Conjunction Jupiter": "You feel emotional expansion and optimism with your partner. They bring wisdom and growth to your emotional life, while you provide emotional depth to their expansive nature, creating mutual support and the ability to help each other grow emotionally and spiritually.",
            "Moon Opposition Jupiter": "You may feel tension between your emotional needs and your partner's philosophical outlook. They might be overly optimistic about your emotional issues, while you feel judged, requiring balance between emotion and wisdom to create harmony.",
            "Moon Trine Jupiter": "You share excellent emotional growth and happiness with your partner. They support and encourage your emotional well-being, while you provide emotional grounding to their expansive energy, fostering mutual support, optimism, and healing.",
            "Moon Sextile Jupiter": "You feel gentle, supportive energy for emotional expansion with your partner. They help you see the bigger picture of your emotional experiences, while you provide emotional wisdom to them, fostering mutual encouragement for growth.",
            "Moon Square Jupiter": "You may feel tension between your emotional needs and your partner's expansion. They might minimize your emotional concerns, while you feel overwhelmed by their optimism, requiring balance between honoring emotions and maintaining a positive perspective.",
            "Moon Conjunction Saturn": "You feel serious emotional responsibility and potential karmic connection with your partner. They provide structure to your emotional life, while you provide emotional warmth to their disciplined nature, though this can feel restrictive if they are too controlling.",
            "Moon Opposition Saturn": "You may feel tension between your emotional needs and your partner's restrictions. They might criticize or limit your emotional expression, while you feel controlled, creating potential for learning emotional maturity and boundaries through challenges.",
            "Moon Trine Saturn": "You share stable, supportive emotional structure with your partner. They provide emotional security to you, while you provide warmth to their structured approach, creating mutual emotional maturity and the ability to build lasting emotional bonds.",
            "Moon Sextile Saturn": "You feel gentle, supportive energy for emotional stability with your partner. They help you develop emotional maturity, while you provide insight to them, fostering mutual support for growth and responsibility.",
            "Moon Square Saturn": "You may experience challenging tension between your emotional needs and your partner's limitations. They might be too critical of your emotional expression, while you feel deprived, creating potential for developing emotional strength through working through difficulties.",
            "Moon Conjunction Uranus": "You share exciting but potentially unstable emotional connection with your partner. They bring innovation to your emotional life, while you provide depth to their revolutionary energy, creating emotional stimulation but also potential for sudden changes or instability.",
            "Moon Opposition Uranus": "You may feel tension between your need for emotional security and your partner's need for change. They might disrupt your stability, while you try to control their freedom, creating exciting but erratic emotional dynamics that require adaptability.",
            "Moon Trine Uranus": "You share harmonious emotional innovation and growth with your partner. They help you break free from emotional limitations, while you provide grounding to their impulses, fostering mutual support for emotional freedom and authentic expression.",
            "Moon Sextile Uranus": "You feel gentle, stimulating energy for emotional growth with your partner. They help you develop emotional independence, while you provide insight to them, fostering mutual encouragement for evolution and freedom.",
            "Moon Square Uranus": "You may feel tension between your emotional needs and your partner's rebellion. They might destabilize you emotionally, while you try to control their unpredictability, creating potential for breaking free from emotional patterns through challenges.",
            "Moon Conjunction Neptune": "You share deep emotional and spiritual connection with your partner, with potential for idealization. They may idealize you or provide spiritual inspiration, while you provide emotional depth to their dreams, creating profound connection but also potential for confusion or deception.",
            "Moon Opposition Neptune": "You may feel tension between your emotional reality and your partner's illusions. They might confuse or deceive you emotionally, while you feel misled, creating potential for romantic fantasy but also disillusionment if not grounded in reality.",
            "Moon Trine Neptune": "You share harmonious emotional and spiritual connection with your partner. They inspire and elevate your emotional and spiritual life, while you provide grounding to their dreams, fostering mutual support with healthy boundaries and profound understanding.",
            "Moon Sextile Neptune": "You feel gentle, inspiring energy for emotional and spiritual growth with your partner. They help you connect with your intuitive side, while you provide wisdom to them, fostering mutual support for development and spiritual insight.",
            "Moon Square Neptune": "You may feel confusion between your emotional needs and your partner's illusions. They might confuse or deceive you emotionally, while you have unrealistic expectations, creating potential for disappointment if not handled with awareness and clear boundaries.",
            "Moon Conjunction Pluto": "You share intensely powerful emotional connection with your partner, with transformative potential. They have a profound impact on your emotional life, while you trigger their deepest psychological processes, creating magnetic attraction but also potential for manipulation or obsession.",
            "Moon Opposition Pluto": "You may feel intense emotional polarity and potential for power struggles with your partner. They might try to control or transform you emotionally, while you feel overwhelmed, creating passionate but potentially destructive dynamics that require awareness and respect.",
            "Moon Trine Pluto": "You share harmonious emotional transformation and empowerment with your partner. They support your emotional healing, while you provide depth to their process, fostering mutual support for growth and profound emotional understanding.",
            "Moon Sextile Pluto": "You feel gentle but powerful energy for emotional transformation with your partner. They help you develop emotional strength, while you provide insight to them, fostering mutual support for empowerment and healing through challenges.",
            "Moon Square Pluto": "You may experience challenging tension involving emotional power and control with your partner. They might try to manipulate you emotionally, while you resist their attempts at transformation, creating potential for profound growth through awareness and respect.",
            "Moon Conjunction Medium Coeli": "Your emotional nature is deeply connected to your partner's career and public image. You intuitively understand what they need emotionally to succeed professionally and provide nurturing support for their ambitions, becoming integral to their professional foundation and offering emotional security.",
            "Moon Opposition Medium Coeli": "Your emotional needs may conflict with your partner's career demands. You might feel neglected when they focus on professional obligations, requiring balance between emotional intimacy and professional success to create harmony.",
            "Moon Trine Medium Coeli": "Your emotional wisdom harmoniously supports your partner's professional goals. You instinctively provide the emotional foundation that allows them to pursue their career aspirations, creating beautiful integration between emotional fulfillment and professional achievement.",
            "Moon Sextile Medium Coeli": "You have the opportunity to provide emotional support and intuitive guidance that benefits your partner's career development. Your emotional intelligence can be consciously channeled to support their professional growth, fostering potential for emotional and professional harmony.",
            "Moon Square Medium Coeli": "Your emotional needs may conflict with your partner's professional requirements. You might feel that your well-being is sacrificed for their career success, creating tension between emotional fulfillment and professional achievement that requires understanding and compromise."
        }

    def get_aspect_interpretation(self, aspect_name):
        return self.aspects.get(aspect_name, "Aspect interpretation not found.")

    def add_aspect(self, aspect_name, interpretation):
        self.aspects[aspect_name] = interpretation

    def remove_aspect(self, aspect_name):
        if aspect_name in self.aspects:
            del self.aspects[aspect_name]
