class NeptuneSynastryAspects:
    def __init__(self):
        self.aspects = {
            "Neptune Conjunction Sun": "You idealize and spiritualize your partner's identity, while they feel inspired and uplifted by your vision. This creates a romantic and spiritually-oriented relationship, but be mindful of potential illusions about each other's true nature.",
            "Neptune Opposition Sun": "You may feel tension between your partner's ego and your illusions. They might feel misunderstood by your vagueness, while you find them too harsh, creating confusion about reality versus idealism in your relationship.",
            "Neptune Trine Sun": "You naturally inspire your partner's creativity and spiritual growth, while they help you manifest your dreams. This creates an inspiring and spiritually enriching relationship with harmonious spiritual inspiration.",
            "Neptune Sextile Sun": "You help your partner connect with their spiritual side, while they help you manifest your dreams practically. This creates a supportive and creatively inspiring dynamic with gentle spiritual inspiration.",
            "Neptune Square Sun": "You may experience confusion and disillusionment with your partner. Your illusions clash with their need for clarity, creating misunderstandings about intentions and identity that require honest communication.",
            "Neptune Conjunction Moon": "You deeply understand your partner's emotional and psychic nature, while they nurture your dreams and spirituality. This creates a psychic and emotionally merged relationship with potential for codependency or emotional confusion.",
            "Neptune Opposition Moon": "You may feel emotionally drained or confused by your partner's vagueness, while they find you too emotionally demanding. This creates challenging emotional dynamics that require boundaries and understanding.",
            "Neptune Trine Moon": "You naturally understand your partner's emotional needs with compassion, while they provide emotional foundation for your spirituality. This creates a deeply empathetic and spiritually connected relationship.",
            "Neptune Sextile Moon": "You help your partner connect with their intuition and dreams, while they add emotional depth to your spiritual nature. This creates a supportive and emotionally enriching dynamic with gentle emotional inspiration.",
            "Neptune Square Moon": "You may experience emotional confusion and psychic overwhelm with your partner. Your emotional vagueness clashes with their need for emotional security, requiring emotional boundaries and clarity.",
            "Neptune Conjunction Ascendant": "You have a significant spiritual or confusing influence on your partner's self-presentation and life direction. This creates a mystical and romantic relationship where they may feel idealized or confused about their identity.",
            "Neptune Opposition Ascendant": "You may feel tension between your partner's natural expression and your illusions. They might feel misunderstood by you, while you find them too mundane, creating a dynamic that requires understanding and balance.",
            "Neptune Trine Ascendant": "You naturally inspire your partner's spiritual development and creativity, while they appreciate your sensitivity and vision. This creates an inspiring and spiritually oriented relationship with harmonious spiritual inspiration.",
            "Neptune Sextile Ascendant": "You offer helpful spiritual guidance to your partner's self-development, while they bring clarity to your vague nature. This creates a supportive and spiritually enriching dynamic with gentle spiritual influence.",
            "Neptune Square Ascendant": "You may experience confusion and unrealistic expectations with your partner. Your illusions clash with their natural expression, creating misunderstandings about identity that require clarity and honesty.",
            "Neptune Conjunction Mercury": "You inspire your partner's imagination and intuitive thinking, while they help you articulate your dreams and visions. This creates psychic communication but potential for mental confusion that requires awareness.",
            "Neptune Opposition Mercury": "You may feel mental confusion and communication problems with your partner. They might feel their thoughts are clouded by your vagueness, while you find them too logical, requiring clarity and honesty in your communication.",
            "Neptune Trine Mercury": "You naturally inspire your partner's imagination and spiritual thinking, while they help you express your visions clearly. This creates poetic and spiritually enriching communication with harmonious intuitive connection.",
            "Neptune Sextile Mercury": "You help your partner develop intuition and creativity, while they add clarity to your abstract thinking. This creates a supportive and creatively inspiring mental dynamic with gentle mental inspiration.",
            "Neptune Square Mercury": "You may experience mental confusion and miscommunication with your partner. Your vague communication clashes with their need for clarity, creating misunderstandings that require honest and clear dialogue.",
            "Neptune Conjunction Venus": "You idealize and spiritualize your partner's love nature, while they find you romantically enchanting. This creates a deeply romantic and idealistic relationship with potential for illusion about love that requires grounding.",
            "Neptune Opposition Venus": "You may feel tension between your need for tangible love and your partner's idealistic love expression. They might feel confused by your vagueness, while you find them too materialistic, creating a dynamic that requires balance and understanding.",
            "Neptune Trine Venus": "You naturally inspire your partner's compassionate love nature, while they bring beauty and grace to your spiritual ideals. This creates a deeply romantic and spiritually connected relationship with harmonious romantic idealism.",
            "Neptune Sextile Venus": "You help your partner express love more spiritually and creatively, while they add beauty and harmony to your dreams. This creates a supportive and artistically inspiring romantic dynamic with gentle romantic inspiration.",
            "Neptune Square Venus": "You may experience romantic confusion and unrealistic expectations with your partner. Your idealistic love clashes with their need for tangible affection, creating disappointment that requires clarity and realistic expectations.",
            "Neptune Conjunction Mars": "You inspire and confuse your partner's energy and desires, while they energize your dreams and spiritual goals. This creates a passionate and idealistic relationship with potential for misdirected energy that requires awareness.",
            "Neptune Opposition Mars": "You may feel tension between your partner's direct action and your indirect, spiritual approach. They might feel frustrated by your vagueness, while you find them too aggressive, creating a dynamic that requires balance and understanding.",
            "Neptune Trine Mars": "You naturally inspire your partner's actions with spiritual vision, while they help you manifest your dreams through action. This creates a spiritually motivated and compassionate relationship with harmonious spiritual action.",
            "Neptune Sextile Mars": "You help your partner connect their actions with spiritual purpose, while they add energy to your spiritual goals. This creates a supportive and spiritually motivated dynamic with gentle spiritual inspiration.",
            "Neptune Square Mars": "You may experience misdirected energy and confused action with your partner. Your vague direction clashes with their need for clear goals, creating frustration that requires clarity about spiritual versus practical goals.",
            "Neptune Conjunction Jupiter": "Your spirituality combines with your partner's wisdom, creating a highly idealistic and spiritually oriented relationship with shared dreams and compassionate vision for growth that requires grounding in reality.",
            "Neptune Opposition Jupiter": "You may feel tension between your partner's philosophical optimism and your mystical idealism. They might find you too vague, while you find them too dogmatic, creating a dynamic that requires balance and understanding.",
            "Neptune Trine Jupiter": "You naturally inspire your partner's spiritual growth and compassion, while they add optimism to your dreams. This creates an inspiring and spiritually expansive relationship with harmonious spiritual expansion.",
            "Neptune Sextile Jupiter": "You help your partner develop spiritual wisdom and compassion, while they help you expand your spiritual vision. This creates a supportive and spiritually enriching dynamic with gentle spiritual growth.",
            "Neptune Square Jupiter": "You may experience conflicting idealism and excessive dreams with your partner. Your philosophical approach clashes with their mystical idealism, creating confusion that requires clarity and realistic expectations.",
            "Neptune Conjunction Saturn": "Your dreams meet your partner's practical structure, creating tension between idealism and reality. You might feel responsible for grounding their visions, while they soften your rigidity, fostering a dynamic of balance and growth.",
            "Neptune Opposition Saturn": "You may feel extreme tension between your partner's realism and your idealism. They might feel frustrated by your impracticality, while you find them too harsh, creating a dynamic that requires balance and understanding.",
            "Neptune Trine Saturn": "You naturally inspire your partner's spiritual development, while they help you manifest your dreams practically. This creates a spiritually grounded and disciplined relationship with harmonious spiritual discipline.",
            "Neptune Sextile Saturn": "You help your partner develop compassion and spiritual awareness, while they help you structure your dreams realistically. This creates a supportive and spiritually practical dynamic with gentle spiritual grounding.",
            "Neptune Square Saturn": "You may experience conflicting approaches to reality and dreams with your partner. Your idealistic visions clash with their practical limitations, creating tension that requires balance and understanding.",
            "Neptune Conjunction Uranus": "Your spirituality combines with your partner's innovation, creating a progressive and spiritually revolutionary relationship with shared interest in transforming consciousness and society that requires grounding.",
            "Neptune Opposition Uranus": "You may feel tension between your partner's revolutionary ideas and your spiritual idealism. They might find you too passive, while you find them too disruptive, creating a dynamic that requires balance and understanding.",
            "Neptune Trine Uranus": "You naturally inspire your partner's humanitarian vision, while they add innovation to your spiritual ideals. This creates a progressive and spiritually revolutionary relationship with harmonious spiritual innovation.",
            "Neptune Sextile Uranus": "You help your partner connect their innovations with spiritual purpose, while they add fresh perspective to your spiritual vision. This creates a supportive and progressively spiritual dynamic with gentle spiritual inspiration.",
            "Neptune Square Uranus": "You may experience disruptive idealism and conflicting visions with your partner. Your mystical approach clashes with their revolutionary methods, creating unpredictable tension that requires clarity and understanding.",
            "Neptune Conjunction Neptune": "You share spiritual ideals and similar approaches to dreams and illusions with your partner. This creates a mutually understanding and spiritually connected relationship with shared dreams that requires grounding in reality.",
            "Neptune Opposition Neptune": "You may experience conflicting spiritual approaches and competing ideals with your partner. You both are idealistic but disagree on spiritual methods, creating tension that requires balance and understanding.",
            "Neptune Trine Neptune": "You naturally understand each other's spiritual needs and dreams with your partner. This creates a supportive and mystically connected relationship with mutual spiritual growth that requires grounding in reality.",
            "Neptune Sextile Neptune": "You appreciate each other's spirituality while offering different perspectives on dreams and idealism with your partner. This creates a supportive and spiritually enriching dynamic that requires grounding in reality.",
            "Neptune Square Neptune": "You may experience clashing spiritual ideals and competing dreams with your partner. You both are idealistic but disagree on spiritual approaches, creating confusion that requires clarity and understanding.",
            "Neptune Conjunction Pluto": "Your spirituality combines with your partner's transformative power, creating an intense and mystical relationship with shared interest in spiritual transformation that requires grounding and awareness.",
            "Neptune Opposition Pluto": "You may feel tension between your idealistic spirituality and your partner's intense transformation. They might find you too passive, while you find them too intense, creating a dynamic that requires balance and understanding.",
            "Neptune Trine Pluto": "You naturally inspire your partner's spiritual transformation, while they add depth to your spiritual ideals. This creates a powerful and spiritually transformative relationship with harmonious spiritual transformation.",
            "Neptune Sextile Pluto": "You help your partner connect transformation with spiritual purpose, while they add depth to your spiritual vision. This creates a supportive and spiritually empowering dynamic with gentle spiritual transformation.",
            "Neptune Square Pluto": "You may experience conflicting spiritual approaches and destructive idealism with your partner. Your passive spirituality clashes with their intense transformation, creating tension that requires clarity and understanding.",
            "Neptune Conjunction Medium Coeli": "Your intuition, creativity, and spiritual insight align perfectly with your partner's career development. You bring artistic vision and compassionate understanding to their professional endeavors, becoming instrumental in their spiritually or creatively oriented career path.",
            "Neptune Opposition Medium Coeli": "Your idealistic vision and spiritual approach may conflict with your partner's practical career requirements. You might feel that your intuitive nature doesn't align with their professional demands, creating tension that requires balance and understanding.",
            "Neptune Trine Medium Coeli": "Your creativity, intuition, and spiritual insight naturally support your partner's professional goals. You provide excellent artistic vision and inspirational qualities that enhance their career success, creating harmonious integration of spiritual insight.",
            "Neptune Sextile Medium Coeli": "You have the opportunity to contribute creativity and spiritual insight to your partner's career development. Your intuitive nature can be consciously applied to support their professional advancement, offering potential for inspired professional achievements.",
            "Neptune Square Medium Coeli": "Your idealistic approach and spiritual vision may clash with your partner's practical career requirements. You might feel that your intuitive nature conflicts with their professional demands, creating friction that requires balance and understanding."
        }

    def get_aspect_interpretation(self, aspect_name):
        return self.aspects.get(aspect_name, "Aspect interpretation not found.")

    def add_aspect(self, aspect_name, interpretation):
        self.aspects[aspect_name] = interpretation

    def remove_aspect(self, aspect_name):
        if aspect_name in self.aspects:
            del self.aspects[aspect_name]
