class SaturnSynastryAspects:
    def __init__(self):
        self.aspects = {
            "Saturn Conjunction Sun": "You bring stability and structure to your partner's self-expression, while they energize your discipline. This creates a serious and committed relationship with potential for long-term growth, though it may feel restrictive initially.",
            "Saturn Opposition Sun": "You may feel tension between your partner's ego and your limitations. They might feel criticized or restricted by you, while you find them too self-centered, creating challenging but potentially maturing dynamics.",
            "Saturn Trine Sun": "You naturally support your partner's goals with practical wisdom, while they give you confidence and purpose. This creates stable, respectful, and long-lasting relationships with harmonious structure and mutual support.",
            "Saturn Sextile Sun": "You offer gentle guidance and mutual respect to your partner. They appreciate your wisdom, while you provide helpful structure to their ambitions, fostering supportive and building relationships.",
            "Saturn Square Sun": "You may experience frustrating obstacles and criticism with your partner. Your restrictions clash with their self-expression, creating feelings of inadequacy that require patience and understanding to overcome.",
            "Saturn Conjunction Moon": "You provide emotional security and structure to your partner's feelings, while they soften your rigidity. This creates stable but potentially restrictive emotional bonds that build security over time with effort.",
            "Saturn Opposition Moon": "You may feel emotional distance versus your partner's need for security. They might feel emotionally blocked by your coldness, while you find them too emotionally demanding, creating tension about emotional expression.",
            "Saturn Trine Moon": "You naturally provide the structure your partner needs for emotional security, while they bring warmth to your discipline. This creates lasting and secure relationships with harmonious emotional stability.",
            "Saturn Sextile Moon": "You help your partner feel more emotionally secure, while they add emotional depth to your practical nature. This creates supportive and nurturing dynamics with gentle emotional grounding.",
            "Saturn Square Moon": "You may experience emotional restriction and criticism with your partner. Your criticism might wound their sensitivity, while their emotions seem irrational to you, creating challenging dynamics that require emotional maturity.",
            "Saturn Conjunction Ascendant": "You have a significant influence on your partner's self-presentation and life direction. This creates serious and committed relationships with potential for personal growth, though they may feel restricted initially.",
            "Saturn Opposition Ascendant": "You may feel tension between your partner's natural expression and your expectations. They might feel criticized or limited by you, while you find them too impulsive, creating challenging but potentially maturing dynamics.",
            "Saturn Trine Ascendant": "You naturally support your partner's development, while they appreciate your wisdom and stability. This creates respectful and growth-oriented relationships with harmonious guidance.",
            "Saturn Sextile Ascendant": "You offer gentle mentorship and mutual respect to your partner. They bring fresh energy to your structured approach, while you provide helpful guidance to their self-development, fostering supportive and building dynamics.",
            "Saturn Square Ascendant": "You may experience frustrating restrictions and criticism with your partner. Your limitations clash with their natural expression, creating feelings of inadequacy that require understanding and patience.",
            "Saturn Conjunction Mercury": "You bring discipline and structure to your partner's thinking and communication, while they help you articulate ideas clearly. This creates serious and thoughtful communication but may feel mentally restrictive initially.",
            "Saturn Opposition Mercury": "You may feel mental tension and communication blocks with your partner. They might feel their ideas are constantly criticized by you, while you find them too scattered, creating challenging mental dynamics.",
            "Saturn Trine Mercury": "You naturally support your partner's learning and communication with practical wisdom, while they help you express ideas more effectively. This creates productive and educational relationships with harmonious mental discipline.",
            "Saturn Sextile Mercury": "You help your partner focus their thoughts, while they add flexibility to your rigid thinking. This creates supportive and learning-oriented dynamics with gentle mental guidance.",
            "Saturn Square Mercury": "You may experience mental frustration and communication obstacles with your partner. Your criticism might block their natural communication style, while their ideas seem impractical to you, creating challenging but potentially growth-oriented dynamics.",
            "Saturn Conjunction Venus": "You bring commitment and stability to your partner's love nature, while they soften your rigidity with affection. This creates serious and long-term relationships but may feel restrictive romantically initially.",
            "Saturn Opposition Venus": "You may feel tension between your partner's need for affection and your emotional distance. They might feel unloved or restricted by you, while you find them too frivolous, creating challenging romantic dynamics.",
            "Saturn Trine Venus": "You naturally provide the stability your partner needs in love, while they bring warmth and beauty to your structured life. This creates enduring and devoted relationships with harmonious romantic grounding.",
            "Saturn Sextile Venus": "You help your partner develop more mature love expressions, while they add grace and affection to your serious nature. This creates supportive and building romantic dynamics with gentle romantic grounding.",
            "Saturn Square Venus": "You may experience romantic restriction and criticism with your partner. Your limitations clash with their need for affection, creating feelings of romantic inadequacy that require understanding and compromise.",
            "Saturn Conjunction Mars": "You discipline and channel your partner's energy, while they energize your goals. This creates productive and goal-oriented partnerships but may feel restrictive to their spontaneity initially.",
            "Saturn Opposition Mars": "You may feel tension between your partner's impulsiveness and your caution. They might feel blocked or criticized by you, while you find them too reckless, creating frustrating but potentially maturing dynamics.",
            "Saturn Trine Mars": "You naturally channel your partner's drive toward productive goals, while they help you take action on plans. This creates efficient and accomplishing relationships with harmonious discipline and directed energy.",
            "Saturn Sextile Mars": "You help your partner focus their energy more effectively, while they add drive to your plans. This creates supportive and building dynamics with gentle structure and motivated action.",
            "Saturn Square Mars": "You may experience frustrating obstacles and blocked energy with your partner. Your restrictions clash with their need for action, creating feelings of limitation that require understanding and patience.",
            "Saturn Conjunction Jupiter": "You ground your partner's expansion with practical wisdom, while they expand your horizons with optimism. This creates balanced growth between expansion and limitation with mutual support.",
            "Saturn Opposition Jupiter": "You may feel tension between your partner's optimism and your realism. They might feel restricted by your pessimism, while you find them too unrealistic, creating challenging but potentially balancing dynamics.",
            "Saturn Trine Jupiter": "You naturally provide a practical framework for your partner's vision, while they add optimism to your discipline. This creates wise and balanced relationships with harmonious structure and mutual support.",
            "Saturn Sextile Jupiter": "You help your partner ground their ideas practically, while they add hope and expansion to your cautious approach. This creates supportive and balanced dynamics with gentle mutual support.",
            "Saturn Square Jupiter": "You may experience conflicting approaches to growth and limitation with your partner. Your restrictions clash with their expansion, creating tension about timing and scope that requires balancing optimism with realism.",
            "Saturn Conjunction Saturn": "You share an approach to responsibility and structure with your partner. Both of you have similar attitudes toward commitment and long-term goals, creating stable and serious relationships with mutual understanding of limitations.",
            "Saturn Opposition Saturn": "You may experience conflicting approaches to structure and responsibility with your partner. Both of you are serious but disagree on methods, creating tension about different approaches to commitment that requires compromise.",
            "Saturn Trine Saturn": "You share harmonious mutual support and values with your partner. Both of you naturally understand each other's need for structure, creating stable and respectful relationships with shared long-term goals.",
            "Saturn Sextile Saturn": "You appreciate each other's discipline while offering different perspectives on responsibility with your partner. This creates supportive and building dynamics with complementary approaches to structure.",
            "Saturn Square Saturn": "You may experience clashing approaches to responsibility and structure with your partner. Both of you are serious but disagree on methods, creating tension that requires compromise and understanding.",
            "Saturn Conjunction Uranus": "You may feel tension between your need for structure and your partner's need for freedom. This creates innovative but potentially unstable dynamics where tradition meets revolution, requiring balance and adaptability.",
            "Saturn Opposition Uranus": "You may feel extreme tension between structure and freedom with your partner. They might feel restricted by your limitations, while you feel threatened by their unpredictability, creating challenging but potentially liberating dynamics.",
            "Saturn Trine Uranus": "You provide a stable framework for your partner's innovations, while they add excitement to your structured life. This creates progressive and stable relationships with harmonious balance between structure and innovation.",
            "Saturn Sextile Uranus": "You help your partner ground their ideas practically, while they add fresh perspective to your approach. This creates supportive and evolving dynamics with gentle balance between tradition and innovation.",
            "Saturn Square Uranus": "You may experience disruptive tension between structure and freedom with your partner. Your restrictions clash with their need for independence, creating unpredictable conflicts that require flexibility and compromise.",
            "Saturn Conjunction Neptune": "You try to structure your partner's dreams and ideals, while they soften your rigidity with compassion. This creates spiritual discipline but potential confusion about reality versus idealism that requires clarity.",
            "Saturn Opposition Neptune": "You may feel tension between your realism and your partner's idealism. They might find you too harsh, while you find them too vague, creating challenging but potentially transcendent dynamics that require balance.",
            "Saturn Trine Neptune": "You help your partner manifest their dreams practically, while they add spiritual dimension to your discipline. This creates inspiring and grounded relationships with harmonious spiritual discipline.",
            "Saturn Sextile Neptune": "You help your partner focus their idealism, while they add sensitivity to your practical approach. This creates supportive and spiritually oriented dynamics with gentle spiritual grounding.",
            "Saturn Square Neptune": "You may experience conflicting approaches to reality and idealism with your partner. Your limitations clash with their dreams, creating confusion about what's practical that requires balancing realism with idealism.",
            "Saturn Conjunction Pluto": "You structure your partner's transformative power, while they intensify your discipline. This creates powerful and transformative relationships with deep commitment but potential for control issues that require awareness.",
            "Saturn Opposition Pluto": "You may feel tension between your control and your partner's transformation. They might feel threatened by your intensity, while you find them too rigid, creating challenging but potentially transformative dynamics that require mutual respect.",
            "Saturn Trine Pluto": "You provide a stable framework for your partner's transformations, while they add depth to your discipline. This creates powerful and enduring relationships with harmonious transformation and structured power.",
            "Saturn Sextile Pluto": "You help your partner channel transformative energy constructively, while they add intensity to your commitment. This creates supportive and empowering dynamics with gentle transformation and disciplined power.",
            "Saturn Square Pluto": "You may experience power struggles and destructive control with your partner. Your restrictions clash with their need for transformation, creating intense conflicts that require conscious transformation and mutual respect.",
            "Saturn Conjunction Saturn": "You share a sense of responsibility and long-term goals with your partner, fostering deep commitment. However, mutual rigidity may lead to stagnation unless you consciously balance and adapt your approaches.",
            "Saturn Opposition Saturn": "You experience a push-pull dynamic around structure and timing with your partner. While your discipline may clash with their resistance, it can serve as a powerful mirror to recognize and resolve patterns, leading to growth through contrast.",
            "Saturn Square Saturn": "You face challenges in dealing with duty and emotional restraint with your partner. It may feel like constant testing, but working through blocks can lead to greater resilience and shared endurance, fostering strength and maturity.",
            "Saturn Trine Saturn": "You share mutual respect and a compatible approach to responsibility with your partner. There's natural ease in supporting each other's goals, building something lasting, though spontaneity may be lacking unless other elements inject excitement.",
            "Saturn Sextile Saturn": "You bring supportive collaboration in building a secure future with your partner. Each of you complements the other's maturity, creating reliability and shared structure, offering a steady foundation for long-term stability."
        }

    def get_aspect_interpretation(self, aspect_name):
        return self.aspects.get(aspect_name, "Aspect interpretation not found.")

    def add_aspect(self, aspect_name, interpretation):
        self.aspects[aspect_name] = interpretation

    def remove_aspect(self, aspect_name):
        if aspect_name in self.aspects:
            del self.aspects[aspect_name]
