class UranusSynastryAspects:
    def __init__(self):
        self.aspects = {
            "Uranus Conjunction Sun": "You bring excitement and innovation to your partner's self-expression, while they energize your unique vision. This creates an electric and stimulating relationship with mutual fascination, though it may feel unstable and resistant to commitment.",
            "Uranus Opposition Sun": "You may feel tension between your partner's ego and your rebellious nature. They might feel disrupted by your unpredictability, while you find them too conventional, creating exciting but potentially unstable dynamics.",
            "Uranus Trine Sun": "You naturally inspire your partner's individuality and creativity, while they support your unique expression. This creates a liberating and progressive relationship with mutual respect for independence and personal growth.",
            "Uranus Sextile Sun": "You help your partner break free from limitations and express their individuality, while they appreciate your originality. This creates a supportive and stimulating dynamic with opportunities for personal growth and freedom.",
            "Uranus Square Sun": "You may experience disruptive tension and conflict with your partner. Your need for freedom clashes with their ego needs, creating unpredictable conflicts that require flexibility and respect for differences.",
            "Uranus Conjunction Moon": "You electrify your partner's emotions and intuition, while they nurture your innovative spirit. This creates an emotionally exciting but potentially unstable relationship with sudden emotional changes and unconventional expression.",
            "Uranus Opposition Moon": "You may feel emotional instability and conflicting needs with your partner. They might feel emotionally disrupted by your unpredictability, while you find them too clingy, creating challenging but potentially liberating dynamics.",
            "Uranus Trine Moon": "You naturally inspire your partner's emotional liberation and psychic abilities, while they provide emotional foundation for your innovations. This creates an emotionally stimulating and free-spirited relationship with mutual growth.",
            "Uranus Sextile Moon": "You help your partner break free from emotional patterns, while they add emotional depth to your detached nature. This creates a supportive and emotionally liberating dynamic with gentle emotional awakening.",
            "Uranus Square Moon": "You may experience emotional disruption and erratic feelings with your partner. Your unpredictability clashes with their need for emotional security, creating sudden upsets and difficulty establishing stability that requires understanding.",
            "Uranus Conjunction Ascendant": "You have a significant liberating or disruptive influence on your partner's self-presentation and life direction. This creates an exciting and unconventional relationship where they feel awakened but potentially destabilized by your influence.",
            "Uranus Opposition Ascendant": "You may feel tension between your partner's natural expression and your rebellious influence. They might feel constantly challenged by you, while you find them too conventional, creating a dynamic of excitement and potential instability.",
            "Uranus Trine Ascendant": "You naturally inspire your partner's individuality and freedom, while they appreciate your originality. This creates a liberating and progressive relationship with mutual respect for personal expression and growth.",
            "Uranus Sextile Ascendant": "You offer helpful liberation from limitations to your partner's self-development, while they bring fresh energy to your innovations. This creates a supportive and awakening dynamic with gentle encouragement and mutual growth.",
            "Uranus Square Ascendant": "You may experience disruptive tension and conflict with your partner. Your innovations clash with their natural expression, creating unpredictable conflicts about freedom versus stability that require flexibility and understanding.",
            "Uranus Conjunction Mercury": "You electrify your partner's thinking and communication, while they help you articulate innovative ideas. This creates mentally stimulating but potentially erratic communication with sudden insights and unconventional thinking that fosters creativity.",
            "Uranus Opposition Mercury": "You may feel mental tension and conflicting communication styles with your partner. They might feel disrupted by your erratic ideas, while you find them too conventional, creating challenging but potentially innovative dynamics.",
            "Uranus Trine Mercury": "You naturally inspire your partner's original thinking and communication, while they help you express your ideas clearly. This creates intellectually stimulating and progressive relationships with harmonious mental connection.",
            "Uranus Sextile Mercury": "You help your partner think outside the box, while they add practical communication skills to your abstract ideas. This creates a supportive and mentally stimulating dynamic with gentle innovation and mutual growth.",
            "Uranus Square Mercury": "You may experience mental disruption and erratic communication with your partner. Your unpredictable thinking clashes with their need for logical communication, creating sudden conflicts that require understanding and adaptability.",
            "Uranus Conjunction Venus": "You bring excitement and unpredictability to your partner's love nature, while they add grace and beauty to your rebellious spirit. This creates a passionate and unconventional relationship with electric attraction but potential commitment issues.",
            "Uranus Opposition Venus": "You may feel tension between your partner's need for harmony and your disruptive nature. They might feel their love needs are constantly disrupted by you, while you find them too possessive, creating a dynamic of excitement and potential instability.",
            "Uranus Trine Venus": "You naturally inspire your partner's independence in love, while they bring beauty and harmony to your unconventional approach. This creates a liberating and exciting romantic relationship with mutual respect for personal expression.",
            "Uranus Sextile Venus": "You help your partner express love more freely and creatively, while they add charm and affection to your detached nature. This creates a supportive and romantically stimulating dynamic with gentle awakening and mutual growth.",
            "Uranus Square Venus": "You may experience romantic disruption and conflicting love styles with your partner. Your need for freedom clashes with their need for romantic security, creating unpredictable conflicts and difficulty with commitment that require understanding.",
            "Uranus Conjunction Mars": "You electrify your partner's energy and ambition, while they energize your revolutionary ideas. This creates a dynamic and action-oriented relationship with shared interest in breaking boundaries but potential for explosive conflicts.",
            "Uranus Opposition Mars": "You may feel tension between your partner's direct action and your erratic energy. They might feel frustrated by your unpredictability, while you find them too aggressive, creating exciting but potentially volatile dynamics.",
            "Uranus Trine Mars": "You naturally inspire your partner's independence and original approach, while they help you take action on your innovations. This creates a dynamic and progressive relationship with mutual respect for personal expression and growth.",
            "Uranus Sextile Mars": "You help your partner break free from conventional approaches, while they add energy and drive to your ideas. This creates a supportive and action-oriented dynamic with gentle revolutionary motivation and mutual growth.",
            "Uranus Square Mars": "You may experience explosive tension and erratic action with your partner. Your unpredictable energy clashes with their need for directed action, creating sudden conflicts and difficulty coordinating efforts that require understanding.",
            "Uranus Conjunction Jupiter": "Your innovation combines with your partner's expansion, creating a progressive and freedom-loving relationship with shared interest in breaking traditional boundaries and exploring new philosophies that foster mutual growth.",
            "Uranus Opposition Jupiter": "You may feel tension between your partner's traditional wisdom and your revolutionary ideas. They might find you too disruptive, while you find them too conventional, creating a dynamic of excitement and potential instability.",
            "Uranus Trine Jupiter": "You naturally inspire your partner's progressive ideals, while they add optimism and broad perspective to your innovations. This creates an inspiring and forward-thinking relationship with mutual respect for personal expression and growth.",
            "Uranus Sextile Jupiter": "You help your partner expand in new directions, while they add wisdom and optimism to your rebellious nature. This creates a supportive and progressively expanding dynamic with gentle growth and mutual understanding.",
            "Uranus Square Jupiter": "You may experience disruptive expansion and conflicting freedoms with your partner. Your revolutionary approach clashes with their traditional expansion, creating unpredictable tension that requires understanding and adaptability.",
            "Uranus Conjunction Saturn": "Your innovation meets your partner's structure, creating tension between revolution and tradition. You might feel responsible for controlling their chaos, while they rebel against your limitations, fostering a dynamic of growth through challenge.",
            "Uranus Opposition Saturn": "You may feel extreme tension between your partner's control and your freedom. They might feel threatened by your unpredictability, while you feel restricted by their limitations, creating challenging but potentially revolutionary dynamics.",
            "Uranus Trine Saturn": "You naturally inspire your partner's progressive development, while they help you structure your innovations practically. This creates a balanced and progressively stable relationship with mutual respect for personal expression and growth.",
            "Uranus Sextile Saturn": "You help your partner break free from rigid patterns, while they help you ground your ideas practically. This creates a supportive and progressively building dynamic with gentle revolutionary grounding and mutual growth.",
            "Uranus Square Saturn": "You may experience disruptive tension between structure and freedom with your partner. Your need for liberation clashes with their need for control, creating unpredictable conflicts that require understanding and adaptability.",
            "Uranus Conjunction Uranus": "You share a revolutionary spirit and similar approaches to freedom and innovation with your partner. This creates a mutually understanding and progressive relationship with shared rebellious ideals that foster personal growth and mutual respect.",
            "Uranus Opposition Uranus": "You may experience conflicting approaches to freedom and competing rebellions with your partner. Both of you are independent but disagree on methods, creating tension that requires understanding and adaptability for mutual growth.",
            "Uranus Trine Uranus": "You naturally understand each other's need for freedom and originality with your partner. This creates a supportive and progressive relationship with mutual respect for independence and personal expression that fosters growth.",
            "Uranus Sextile Uranus": "You appreciate each other's originality while offering different perspectives on freedom and rebellion with your partner. This creates a supportive and progressively stimulating dynamic with gentle mutual liberation and growth.",
            "Uranus Square Uranus": "You may experience clashing freedoms and competing innovations with your partner. Both of you are rebellious but disagree on methods, creating unpredictable tension that requires understanding and adaptability for mutual growth.",
            "Uranus Conjunction Neptune": "Your innovation combines with your partner's spirituality, creating a progressive and spiritually revolutionary relationship with shared interest in transforming consciousness and transcending limitations that foster mutual growth.",
            "Uranus Opposition Neptune": "You may feel tension between your revolutionary clarity and your partner's mystical vagueness. They might find you too disruptive, while you find them too passive, creating a dynamic of excitement and potential instability that requires understanding.",
            "Uranus Trine Neptune": "You naturally inspire your partner's spiritual revolution, while they add spiritual depth to your innovations. This creates an inspiring and spiritually progressive relationship with mutual respect for personal expression and growth.",
            "Uranus Sextile Neptune": "You help your partner revolutionize their spiritual approach, while they add spiritual sensitivity to your rebellious nature. This creates a supportive and spiritually innovative dynamic with gentle awakening and mutual growth.",
            "Uranus Square Neptune": "You may experience disruptive spirituality and conflicting visions with your partner. Your revolutionary approach clashes with their mystical idealism, creating unpredictable tension that requires understanding and adaptability for mutual growth.",
            "Uranus Conjunction Pluto": "Your innovation combines with your partner's transformative power, creating an intense and revolutionary relationship with shared interest in radical transformation and breaking down old structures that foster mutual growth.",
            "Uranus Opposition Pluto": "You may feel tension between your rebellious freedom and your partner's intense transformation. They might find you too erratic, while you find them too intense, creating a dynamic of excitement and potential instability that requires understanding.",
            "Uranus Trine Pluto": "You naturally inspire your partner's progressive transformation, while they add depth and intensity to your innovations. This creates a powerful and transformative relationship with mutual respect for personal expression and growth.",
            "Uranus Sextile Pluto": "You help your partner revolutionize their approach to transformation, while they add intensity and depth to your rebellious nature. This creates a supportive and transformatively progressive dynamic with gentle empowerment and mutual growth.",
            "Uranus Square Pluto": "You may experience explosive transformation and disruptive power with your partner. Your need for freedom clashes with their intense transformation, creating unpredictable conflicts that require understanding and adaptability for mutual growth.",
            "Uranus Conjunction Medium Coeli": "Your innovative spirit and originality align perfectly with your partner's career development. You bring unique perspectives and breakthrough thinking to their professional endeavors, becoming instrumental in their unconventional career path or revolutionary achievements.",
            "Uranus Opposition Medium Coeli": "Your need for freedom may conflict with your partner's career stability requirements. You might feel that your innovative spirit doesn't align with their professional constraints, creating tension between innovation and stability that requires understanding.",
            "Uranus Trine Medium Coeli": "Your innovation and originality naturally support your partner's professional goals. You provide excellent insights and breakthrough thinking that enhance their career success, creating harmonious integration of innovation and achievement.",
            "Uranus Sextile Medium Coeli": "You have the opportunity to contribute innovation to your partner's career development. Your originality can be consciously applied to support their professional advancement, offering potential for breakthrough achievements with mutual growth.",
            "Uranus Square Medium Coeli": "Your revolutionary approach may clash with your partner's career requirements. You might feel that your innovative spirit conflicts with their professional stability needs, creating friction that requires understanding and adaptability for mutual growth."
        }

    def get_aspect_interpretation(self, aspect_name):
        return self.aspects.get(aspect_name, "Aspect interpretation not found.")

    def add_aspect(self, aspect_name, interpretation):
        self.aspects[aspect_name] = interpretation

    def remove_aspect(self, aspect_name):
        if aspect_name in self.aspects:
            del self.aspects[aspect_name]
