class VenusSynastryAspects:
    def __init__(self):
        self.aspects = {
            "Venus Conjunction Sun": "You feel naturally loving and affectionate toward your partner's identity. You find them attractive and appealing, creating harmony between love and identity. Your affection feels welcomed and appreciated by them.",
            "Venus Opposition Sun": "You may feel tension between your way of loving and your partner's ego expression. You might need to adjust your loving approach to match their identity, or feel your affection is not reciprocated as you prefer.",
            "Venus Trine Sun": "You feel naturally appreciated and loved by your partner. Their identity harmonizes with your way of expressing love, creating easy affection and mutual appreciation that strengthens your bond.",
            "Venus Sextile Sun": "You feel gently appreciated and supported by your partner. There's mutual support for love and beauty, with your affection feeling valued and understood by them.",
            "Venus Square Sun": "You may feel your way of loving conflicts with your partner's ego needs. Their identity might clash with your values or aesthetic preferences, creating tension in how love is expressed and received.",
            "Venus Conjunction Moon": "You feel deeply emotionally connected and loving toward your partner. Their emotional nature aligns with how you express love, creating deep romantic and emotional harmony that nurtures your relationship.",
            "Venus Opposition Moon": "You may feel your love style differs from your partner's emotional needs. While there's attraction, you might need to learn different ways of expressing love to meet their emotional requirements, fostering growth through understanding.",
            "Venus Trine Moon": "You feel naturally emotionally supported and appreciated by your partner. Their emotional responses enhance your ability to love and feel loved, creating harmonious romantic flow and deep connection.",
            "Venus Sextile Moon": "You feel gently emotionally supported by your partner. There's mutual emotional understanding, helping you express love in ways that feel nurturing and caring, fostering a supportive and affectionate bond.",
            "Venus Square Moon": "You may feel your way of loving doesn't match your partner's emotional needs. Their emotional intensity might overwhelm your more gentle approach to love, requiring understanding and adaptability.",
            "Venus Conjunction Ascendant": "You feel immediately attracted to and loving toward your partner's natural presentation. Their way of being appeals to your aesthetic and romantic sensibilities, creating an instant connection and mutual appreciation.",
            "Venus Opposition Ascendant": "You may see your partner as representing your romantic ideals. You might idealize them or feel they embody everything you want in a partner, fostering a dynamic of admiration and potential growth.",
            "Venus Trine Ascendant": "You feel naturally attracted to and appreciative of your partner. Their natural presentation harmonizes with your aesthetic and romantic preferences, creating a supportive and affectionate bond.",
            "Venus Sextile Ascendant": "You feel gently attracted to and appreciative of your partner. There's mutual appreciation, enhancing each other's attractiveness and charm, fostering a harmonious and affectionate connection.",
            "Venus Square Ascendant": "You may feel your aesthetic or romantic preferences conflict with your partner's natural presentation. Their way of being might clash with your values or ideals, creating tension that requires understanding and compromise.",
            "Venus Conjunction Mercury": "You feel appreciated and loved for your aesthetic and romantic nature by your partner. Their communication style appeals to your need for harmony and beauty in expression, creating a supportive and affectionate dynamic.",
            "Venus Opposition Mercury": "You may feel your romantic values conflict with your partner's analytical approach. They might seem too critical for your preference for harmony, creating a dynamic that requires balance and understanding.",
            "Venus Trine Mercury": "You feel naturally appreciated and understood by your partner's communication style. They enhance your ability to express love beautifully and harmoniously, fostering a deep and affectionate connection.",
            "Venus Sextile Mercury": "You feel gently appreciated and supported by your partner's communication. There's mutual support for beautiful expression and harmonious communication, creating a pleasant and affectionate bond.",
            "Venus Square Mercury": "You may feel criticized or unappreciated by your partner's analytical communication style. They might seem too harsh for your preference for gentle interaction, creating tension that requires understanding and adaptability.",
            "Venus Conjunction Mars": "You feel intensely attracted to and passionate about your partner's energy and assertiveness. They stimulate your romantic and sexual nature, creating strong physical and romantic chemistry, though they may sometimes be too aggressive for your preference for harmony.",
            "Venus Opposition Mars": "You may feel both attracted to and challenged by your partner's assertive energy. Their assertiveness might clash with your need for harmony, creating a dynamic of excitement and potential growth through understanding.",
            "Venus Trine Mars": "You feel naturally attracted to and connected with your partner's passionate energy. Their assertiveness enhances your romantic nature without overwhelming your need for harmony, fostering a passionate yet balanced relationship.",
            "Venus Sextile Mars": "You feel gently attracted to and supported by your partner's energy. There's mutual support for romantic and sexual expression, with them helping you feel more confident in love, creating a dynamic of affection and mutual growth.",
            "Venus Square Mars": "You may feel overwhelmed by your partner's aggressive approach to love and sexuality. Their directness might clash with your preference for gentle romantic expression, creating tension that requires understanding and adaptability.",
            "Venus Conjunction Jupiter": "You feel expanded and elevated by your partner's optimistic and generous nature. They enhance your capacity for love and bring joy to your romantic life, creating a relationship full of mutual appreciation for beauty and culture.",
            "Venus Opposition Jupiter": "You may feel overwhelmed by your partner's grand gestures or philosophical approach to love. They might be too expansive for your more personal approach to romance, creating a dynamic that requires balance and understanding.",
            "Venus Trine Jupiter": "You feel naturally supported and elevated by your partner's wisdom and generosity. They enhance your happiness and bring growth to your love life, creating a harmonious and joyful relationship full of mutual appreciation.",
            "Venus Sextile Jupiter": "You feel gently supported and encouraged by your partner's optimistic nature. There's mutual support for happiness and growth, with them helping you expand your capacity for love and joy, fostering a dynamic of affection and mutual growth.",
            "Venus Square Jupiter": "You may feel pressured by your partner's moral or philosophical standards about love. They might be too excessive for your more refined approach to romance, creating tension that requires understanding and adaptability.",
            "Venus Conjunction Saturn": "You feel both supported and restricted by your partner's serious approach to love. They provide stability to your romantic life but may also feel cold or limiting, creating a dynamic of commitment and potential growth through understanding.",
            "Venus Opposition Saturn": "You may feel judged or restricted by your partner's serious approach to love. They might seem too cold for your need for warmth and appreciation in romance, creating tension that requires understanding and adaptability.",
            "Venus Trine Saturn": "You feel naturally supported and stabilized by your partner's reliable approach to love. They provide security that allows your love to flourish within stable boundaries, fostering a relationship of commitment and mutual growth.",
            "Venus Sextile Saturn": "You feel gently supported and encouraged by your partner's stability. There's mutual support for committed love and the ability to build lasting romantic connections, creating a dynamic of affection and mutual growth.",
            "Venus Square Saturn": "You may feel criticized or restricted by your partner's serious approach to love. They might seem too cold or demanding, while you feel your romantic expression is being limited, creating tension that requires understanding and adaptability.",
            "Venus Conjunction Uranus": "You feel excited and liberated by your partner's unconventional approach to love. They bring innovation and freedom to your romantic life, though this can also create instability, fostering a dynamic of excitement and potential growth through understanding.",
            "Venus Opposition Uranus": "You may feel both attracted to and destabilized by your partner's unpredictable approach to love. They might be too erratic for your need for stable romance, creating a dynamic of excitement and potential growth through understanding.",
            "Venus Trine Uranus": "You feel naturally inspired and liberated by your partner's original approach to love. They enhance your romantic creativity and help you express love in new ways, fostering a dynamic of excitement and mutual growth.",
            "Venus Sextile Uranus": "You feel gently inspired and supported by your partner's innovative approach to love. There's mutual support for creative romance and the ability to express love in original ways, creating a dynamic of affection and mutual growth.",
            "Venus Square Uranus": "You may feel disrupted by your partner's erratic approach to love. They might be too unpredictable for your need for stable romance, creating tension that requires understanding and adaptability for mutual growth.",
            "Venus Conjunction Neptune": "You feel spiritually elevated and romantically inspired by your partner's dreamy nature. They enhance your romantic imagination but may also create unrealistic expectations, fostering a dynamic of depth and potential growth through understanding.",
            "Venus Opposition Neptune": "You may feel confused by your partner's elusive approach to love. They might seem too dreamy for your need for tangible expressions of love, creating a dynamic that requires clarity and understanding for mutual growth.",
            "Venus Trine Neptune": "You feel naturally inspired and spiritually supported by your partner's romantic idealism. They enhance your capacity for unconditional love without creating harmful illusions, fostering a dynamic of depth and mutual growth.",
            "Venus Sextile Neptune": "You feel gently inspired and supported by your partner's dreamy approach to love. There's mutual support for romantic creativity and spiritual connection, creating a dynamic of affection and mutual growth.",
            "Venus Square Neptune": "You may feel confused by your partner's unclear approach to love. They might create romantic illusions that disappoint your need for genuine affection, creating tension that requires clarity and understanding for mutual growth.",
            "Venus Conjunction Pluto": "You feel intensely transformed by your partner's deep approach to love. They bring profound depth to your romantic life but may also feel overwhelming, fostering a dynamic of intensity and potential growth through understanding.",
            "Venus Opposition Pluto": "You may feel both attracted to and threatened by your partner's intense approach to love. They might be too possessive for your need for harmony, creating a dynamic of intensity and potential growth through understanding.",
            "Venus Trine Pluto": "You feel naturally empowered by your partner's profound approach to love. They enhance your capacity for deep love without overwhelming your need for harmony, fostering a dynamic of depth and mutual growth.",
            "Venus Sextile Pluto": "You feel gently empowered and supported by your partner's deep approach to love. There's mutual support for transformative love and the ability to heal through romance, creating a dynamic of affection and mutual growth.",
            "Venus Square Pluto": "You may feel controlled by your partner's intense approach to love. They might be too possessive for your need for harmonious romance, creating tension that requires understanding and adaptability for mutual growth.",
            "Venus Conjunction Medium Coeli": "Your aesthetic sense and values align perfectly with your partner's career image and professional goals. You bring beauty and social grace to their professional endeavors, becoming instrumental in their social and professional networking and enhancing their appeal.",
            "Venus Opposition Medium Coeli": "Your values and aesthetic preferences may conflict with your partner's career demands. You might feel their professional requirements compromise your shared values, creating tension between personal values and professional achievement that requires understanding.",
            "Venus Trine Medium Coeli": "Your charm and aesthetic sense naturally enhance your partner's professional image. You bring grace and beauty to their professional endeavors, creating harmonious integration between personal values and professional success.",
            "Venus Sextile Medium Coeli": "You have the opportunity to contribute aesthetic insight to your partner's career development. Your sense of beauty can enhance their professional presentation, offering potential for adding grace to their endeavors with mutual growth.",
            "Venus Square Medium Coeli": "Your values and aesthetic preferences may clash with your partner's professional requirements. You might feel their career demands compromise your shared values, creating friction between personal values and professional achievement that requires understanding.",
            "Venus Conjunction Venus": "You share immediate warmth and mutual understanding, expressing affection identically. This fosters strong emotional and aesthetic harmony, creating a cozy and comfortable bond that requires effort to keep exciting.",
            "Venus Opposition Venus": "You feel a strong initial pull but appreciate things differently. If you respect each other's preferences, this polarity can deepen your connection and sexual chemistry, fostering a dynamic of growth and mutual understanding.",
            "Venus Square Venus": "You experience intense attraction but also friction from different tastes and approaches to love. Despite tension, this offers transformative potential if you communicate and adapt, fostering a dynamic of growth and mutual understanding.",
            "Venus Trine Venus": "You share a flowing and harmonious bond with similar values and affection. This eases connection and cooperation, though it might lack excitement unless complemented by more stimulating aspects, creating a dynamic of mutual growth and understanding.",
            "Venus Sextile Venus": "You share similar tastes and comfort around each other, with affection that's easy to express. Though initially less magnetic, this aspect allows gradual growth by learning each other's affectionate cues, fostering a dynamic of mutual understanding and growth."
        }

    def get_aspect_interpretation(self, aspect_name):
        return self.aspects.get(aspect_name, "Aspect interpretation not found.")

    def add_aspect(self, aspect_name, interpretation):
        self.aspects[aspect_name] = interpretation

    def remove_aspect(self, aspect_name):
        if aspect_name in self.aspects:
            del self.aspects[aspect_name]
